# ==================== CONFIG TWEAKING NOTES ===========================
    # NOTE: match NUM_STEPS w/ num_inner_steps for episode length
    # NOTE: match GIF_NUM_FRAMES w/ num_inner_steps and NUM_STEPS if want eval to be full episode length
    # NOTE: run # rollouts (NUM_UPDATES) > 10, bc with new chunk refactor, it will still run 10 chunks of size 1 if NUM_UPDATES < 10

# ====== tiny test (# rollouts = 2)
# "NUM_ENVS": 2
# "NUM_STEPS": 8
# "TOTAL_TIMESTEPS": 32
# "UPDATE_EPOCHS": 1
# "NUM_MINIBATCHES": 1
# "GIF_NUM_FRAMES": 50

# ====== small test (# rollouts = 16)
# "NUM_ENVS": 4
# "NUM_STEPS": 16 # match to num_inner_steps
# "TOTAL_TIMESTEPS": 1024
# "UPDATE_EPOCHS": 2
# "NUM_MINIBATCHES": 2
# "GIF_NUM_FRAMES": 50

# ====== longer ep small test (# rollouts = 16)
# "NUM_ENVS": 4
# "NUM_STEPS": 128
# "TOTAL_TIMESTEPS": 8192
# "UPDATE_EPOCHS": 4
# "NUM_MINIBATCHES": 4
# "GIF_NUM_FRAMES": 50

"LR": 0.0005
# "NUM_ENVS": 256
"NUM_ENVS": 128
"NUM_STEPS": 1000
"TOTAL_TIMESTEPS": 3e8
"UPDATE_EPOCHS": 2
"NUM_MINIBATCHES": 500
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "clean_up"
"REW_SHAPING_HORIZON": 2.5e6 # for how many timesteps add a shaping reward
"SHAPING_BEGIN": 1e6
"ENV_KWARGS": 
  "num_agents" : 7
  "num_inner_steps" : 1000 # NOTE: match to NUM_STEPS
  "shared_rewards" : False  # Attention: switch to False for individual rewards 
  "cnn" : True
  "jit" : True
  

"ANNEAL_LR": True
"SEED": 30
"NUM_SEEDS": 1
"TUNE": True

"REWARD": "individual" # individual; common
"GIF_NUM_FRAMES": 250
"PARAMETER_SHARING": True

# WandB Params
"ENTITY": "rohit-chawla28"
"PROJECT": "socialjax-ippo"
"WANDB_GROUP": "IPPO-individual-cleanup"
"WANDB_MODE" : "online"
"WANDB_TAGS":
  - INDIVIDUAL_REWARD # COMMON_REWARD
